modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="SKD"
authors="SKD"
logoFile="${mod_id}.png"
description='''Carry Mechanics is a mod that allows players to pick up, carry, and place blocks and entities with their bare hands.'''

[[mixins]]
config="carry_mechanics.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"